<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Women</name>
   <tag></tag>
   <elementGuidId>76486b70-1b54-43ef-baf5-41c183487c3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.level0.nav-2.category-item.level-top.parent > a.level-top > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store.menu']/nav/ul/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1533e2ba-5fb2-4a2f-95c0-2defde69ecab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Women</value>
      <webElementGuid>f97b7fdf-e6a2-459e-bfbc-193ac2d9cbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store.menu&quot;)/nav[@class=&quot;navigation&quot;]/ul[1]/li[@class=&quot;level0 nav-2 category-item level-top parent&quot;]/a[@class=&quot;level-top&quot;]/span[1]</value>
      <webElementGuid>3140a2b8-7618-4989-811d-b12206bf1014</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='store.menu']/nav/ul/li[2]/a/span</value>
      <webElementGuid>01fdc00d-9cad-4445-a938-c385add3af59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('What', &quot;'&quot;, 's New')])[1]/following::span[1]</value>
      <webElementGuid>17c9e16e-dc41-40ef-8eec-55d8bebb0f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::span[2]</value>
      <webElementGuid>5ea5b084-9454-4136-b1ba-48a8ec2294e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[1]/preceding::span[1]</value>
      <webElementGuid>b65bb1ab-dd8c-4194-8835-37431341bc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jackets'])[1]/preceding::span[2]</value>
      <webElementGuid>7eb7cf66-c626-4861-bebb-1e1ffd7e09df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Women']/parent::*</value>
      <webElementGuid>894b7cbc-f67b-4a00-8c5f-2af371cadf24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>9b1c41fc-07d5-4f3f-b5c1-fb934d7931aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Women' or . = 'Women')]</value>
      <webElementGuid>31254bf1-21a4-4800-bcb9-5eca4d7c6197</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
