<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_See Details</name>
   <tag></tag>
   <elementGuidId>d34ec5b4-3f7b-4894-9fc6-094d3db875db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='mini-cart']/li/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51c13c86-20ea-4c5f-9590-516baa0b1705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>5b79d784-2250-499b-b42f-3ad8cbd70929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toggle</value>
      <webElementGuid>3c8c9008-efa1-453c-b1dd-73e5cd552f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>085c17cf-59ea-420b-b49c-a6eb3667f421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>86574a74-fccf-42fb-ad9c-2ca3fbb7a752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>840362e4-42f8-4f4c-8b1d-30c2386d071b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a80c3aef-9329-46bf-89c1-9d0f038eaa47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>See Details</value>
      <webElementGuid>e43eaa0b-1f81-4225-b243-cef4caeb7dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mini-cart&quot;)/li[@class=&quot;item product product-item odd last&quot;]/div[@class=&quot;product&quot;]/div[@class=&quot;product-item-details&quot;]/div[@class=&quot;product options&quot;]/span[@class=&quot;toggle&quot;]</value>
      <webElementGuid>9b9fa7d5-407c-445d-ae6d-82c2eabd62e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='mini-cart']/li/div/div/div/span</value>
      <webElementGuid>669d4530-ff45-45ba-b11c-dd744c67a308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hero Hoodie'])[1]/following::span[1]</value>
      <webElementGuid>dbbf0cf4-2103-4c5b-bbb2-f77d8ded6283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recently added item(s)'])[1]/following::span[3]</value>
      <webElementGuid>b4419f1a-462b-4a93-b819-8ac8d8402acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options Details'])[1]/preceding::span[2]</value>
      <webElementGuid>3990031a-459d-480b-a78d-8b114e7947e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/span</value>
      <webElementGuid>3b11e710-b112-4e9a-a041-cbc505db4bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'See Details' or . = 'See Details')]</value>
      <webElementGuid>6dad371d-b102-4d56-938a-0fa91650bec4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
