<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_username</name>
   <tag></tag>
   <elementGuidId>730ef239-d993-4904-9433-5e80e6f0f027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bcdd6e1-edf1-4b9c-854f-f73db47b054d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text mage-error</value>
      <webElementGuid>ae5a8f4a-b921-4a10-af3c-f10ea44ea7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>47da1d5a-8be8-425c-b899-954860d1158b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                            textInput: email,
                            hasFocus: emailFocused</value>
      <webElementGuid>1b9d0573-a907-48ff-b9cb-6bc22c9e63fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>6e2b660d-76d9-484f-ac0e-76c9724dbae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{required:true, 'validate-email':true}</value>
      <webElementGuid>cc64a2aa-753b-4336-b167-77acf8905a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer-email</value>
      <webElementGuid>a9fc2fdf-65ed-46bc-a664-5fd4ca72b9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e485454-1b9c-482c-bac4-df3a256cd038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fc9fc2ef-70b6-46aa-99b7-5c0200d16c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>customer-email-error</value>
      <webElementGuid>51b74c4b-25f7-4418-81d3-d0e65c4d0b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-email-fieldset&quot;)/div[@class=&quot;field required&quot;]/div[@class=&quot;control _with-tooltip&quot;]/input[@id=&quot;customer-email&quot;]</value>
      <webElementGuid>5473da3d-1bcb-4014-b9f6-28485fd6e186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer-email']</value>
      <webElementGuid>5d4d59e9-0674-49a2-b761-7736041afed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='customer-email-fieldset']/div/div/input</value>
      <webElementGuid>5843327d-8928-4d16-908f-67f38fbea613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>79e9a54f-8e3f-4138-89c4-5f285ee8c6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'username' and @id = 'customer-email']</value>
      <webElementGuid>c28b1889-b9b7-4ab4-97a4-5c90937fbe32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
