<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Title_ko_unique_1</name>
   <tag></tag>
   <elementGuidId>99039e92-e931-48bb-85e8-a0560dab2abe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ko_unique_1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ko_unique_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d82f5853-2290-4162-ac08-618baf27859d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8bbf08be-699e-4fa9-94b6-a1a281c1f5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c114f0c1-53c6-48f8-8434-5a55316ba6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {'aria-labelledby': 'label_method_' + method.method_code + '_' + method.carrier_code + ' ' + 'label_carrier_' + method.method_code + '_' + method.carrier_code,
                    'checked': element.rates().length == 1 || element.isSelected}, value: method.carrier_code + '_' + method.method_code, checked: element.isSelected</value>
      <webElementGuid>fe4c2b18-d68d-40e2-ab65-06c5669f7a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_method_bestway_tablerate label_carrier_bestway_tablerate</value>
      <webElementGuid>0353df26-9914-4b56-9894-c139f8e0c59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>tablerate_bestway</value>
      <webElementGuid>91cd13e6-af51-46b9-9407-dfa77f23d942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ko_unique_1</value>
      <webElementGuid>a4fa7060-3054-4729-82be-4a878541497c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-shipping-method-load&quot;)/table[@class=&quot;table-checkout-shipping-method&quot;]/tbody[1]/tr[@class=&quot;row&quot;]/td[@class=&quot;col col-method&quot;]/input[@class=&quot;radio&quot;]</value>
      <webElementGuid>2ee5f60b-72f6-47dc-b067-3e10ddb30c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ko_unique_1']</value>
      <webElementGuid>25a4f3b2-a6f1-40b8-aa69-38bea83cf2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-method-load']/table/tbody/tr/td/input</value>
      <webElementGuid>c15c7c32-a23e-4c54-927a-409d143005bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>84c12cae-f8c9-4421-a620-d2c759e6e971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ko_unique_1']</value>
      <webElementGuid>134e6d47-c95b-4c53-b2a5-d5da12490ef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
