<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Proceed to Checkout</name>
   <tag></tag>
   <elementGuidId>51c335fd-d371-443c-b419-382ba917b6f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Cart > a.button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Cart']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d6b10139-f135-40ee-a4af-a5c72519479d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/order/newOrderForm</value>
      <webElementGuid>9dd23229-c2df-422e-b070-c226d9dfd716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2dc950d-45cb-4e23-844e-9bc5b3b02ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed to Checkout</value>
      <webElementGuid>cc77ef53-11f4-43f7-9352-9b06405cfdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cart&quot;)/a[@class=&quot;button&quot;]</value>
      <webElementGuid>9b54d933-9b92-41b0-aaf5-1357b9a104c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cart']/a</value>
      <webElementGuid>947c4091-4000-4f37-94c8-a68e56caf949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Proceed to Checkout')]</value>
      <webElementGuid>8a1e80cb-d77c-4b3f-a180-fc261619b790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove All'])[1]/following::a[1]</value>
      <webElementGuid>48437deb-dfd2-4500-a3b2-4984ca02feda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$18.50'])[3]/following::a[2]</value>
      <webElementGuid>2923ea8c-d925-4c03-85de-83421cf9b320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aspectran.com'])[1]/preceding::a[1]</value>
      <webElementGuid>56953390-2d62-4008-bfb7-60933bbfbe99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mybatis.org'])[1]/preceding::a[2]</value>
      <webElementGuid>882cf838-8b24-4c97-8682-3a00803def6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed to Checkout']/parent::*</value>
      <webElementGuid>0a746504-c66f-44df-a4a9-608f064af45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/order/newOrderForm')]</value>
      <webElementGuid>791c97e6-e9dc-4c04-821b-400758f1413b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/a</value>
      <webElementGuid>da7f5a69-0f60-4c39-870b-83104dc0e092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/order/newOrderForm' and (text() = 'Proceed to Checkout' or . = 'Proceed to Checkout')]</value>
      <webElementGuid>b6aa2e33-3c0f-4593-af5b-471d67cfc7c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
