<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Remove</name>
   <tag></tag>
   <elementGuidId>599e3187-813f-4ad3-a971-547780eb1c6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Cart']/form/table/tbody/tr[2]/td[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b0b82cb1-5e35-4ecf-846c-d23e684cb41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c609f71d-dddd-4924-a697-e6de29b2e541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart/removeItemFromCart?cartItem=EST-6</value>
      <webElementGuid>23f40fd2-2dcc-429f-b73f-d86eef93f407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>d1158527-e00d-4653-90aa-81d790950949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cart&quot;)/form[1]/table[1]/tbody[1]/tr[2]/td[8]/a[@class=&quot;button&quot;]</value>
      <webElementGuid>a2fb2339-bce4-44c4-bfe5-019523d41ad8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cart']/form/table/tbody/tr[2]/td[8]/a</value>
      <webElementGuid>3acdaecf-1763-4afe-9f26-9ad39d2ebc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Remove')]</value>
      <webElementGuid>e8db4107-38d6-4625-9033-ce16dc277c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$18.50'])[2]/following::a[1]</value>
      <webElementGuid>dda3972b-9bf9-4556-902c-5da9e34c1b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$18.50'])[1]/following::a[1]</value>
      <webElementGuid>53153db6-bed2-4e1b-b6ff-9f948bbd1141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Cart'])[1]/preceding::a[1]</value>
      <webElementGuid>6877333c-463f-4060-b44a-a4e6da5ecb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Total:'])[1]/preceding::a[1]</value>
      <webElementGuid>a5626982-3179-4068-8937-1a07b83495ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove']/parent::*</value>
      <webElementGuid>fcb65333-f478-4fd4-ab62-c3bdc0e17344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cart/removeItemFromCart?cartItem=EST-6')]</value>
      <webElementGuid>3519d423-5b87-41bb-97d7-b0ee35ec277d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a</value>
      <webElementGuid>1b45cec2-b28d-43b7-95fc-bd1b5292184b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cart/removeItemFromCart?cartItem=EST-6' and (text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>6090b4ea-0077-4725-8762-1a9e3c8e9130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
