<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__keyword</name>
   <tag></tag>
   <elementGuidId>4a1e4e0b-2a30-4b58-9e22-d8d99b87931e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SearchContent > form > div.input-group > input[name=&quot;keyword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='keyword'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e12f176c-64ff-4826-9e5c-7f037ba026be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-field</value>
      <webElementGuid>1a8ad874-c6a3-4074-ab36-35cae289db2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9bd3864e-da03-406f-b92a-75fb22238f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>727b1b77-956d-45e1-8c22-fca9ac7acd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Product Search</value>
      <webElementGuid>98db3a1a-3474-4af5-a28a-e6efc1ac386c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchContent&quot;)/form[1]/div[@class=&quot;input-group&quot;]/input[@class=&quot;input-group-field&quot;]</value>
      <webElementGuid>b2f4b1b0-e9a7-41c6-b3b4-784b938e32cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='keyword'])[2]</value>
      <webElementGuid>4bebf5a0-a3c0-4c8a-b17f-729f900b0f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchContent']/form/div/input</value>
      <webElementGuid>cc0d8107-711b-4e63-9c29-a9bde14ce2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div/div[3]/div/form/div/input</value>
      <webElementGuid>6ae9db02-643f-4559-923f-ff21ce6cd89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'keyword' and @placeholder = 'Product Search']</value>
      <webElementGuid>dd6ac341-c1ec-46b8-9440-6050cab36b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
